# Generated by Django 5.1.7 on 2025-07-30 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_english', models.CharField(max_length=100, unique=True, verbose_name='Palavra em Inglês')),
                ('text_portuguese', models.CharField(max_length=100, verbose_name='Tradução Principal')),
                ('synonyms_portuguese', models.TextField(blank=True, null=True, verbose_name='Sinônimos em Português')),
                ('complexity', models.IntegerField(default=0, verbose_name='Complexidade (Comprimento)')),
            ],
        ),
        migrations.CreateModel(
            name='UserWordStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Nao Visto', 'Não Visto'), ('Acertou de Primeira', 'Acertou de Primeira'), ('Em Revisao', 'Em Revisão'), ('Dominado', 'Dominado')], default='Nao Visto', max_length=20)),
                ('consecutive_correct_answers', models.IntegerField(default=0, verbose_name='Acertos Consecutivos')),
                ('next_review_date', models.DateTimeField(blank=True, null=True, verbose_name='Próxima Revisão')),
                ('is_in_training_deck', models.BooleanField(default=False, verbose_name='Está no Deck de Treino?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.word', verbose_name='Palavra')),
            ],
            options={
                'unique_together': {('user', 'word')},
            },
        ),
    ]
